# Generated by Django 4.2 on 2023-05-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('idClase', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('agno', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('idDisciplina', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idProfesor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ci', models.CharField(max_length=11, unique=True, verbose_name='Carnet identidad')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('grado_cientifico', models.CharField(choices=[('ninguno', 'ninguno'), ('master', 'master'), ('doctor', 'doctor')], max_length=255, verbose_name='Grado científico')),
                ('categoria_docente', models.CharField(choices=[('Instructor', 'Instructor'), ('asistente', 'asistente'), ('auxiliar', 'auxiliar'), ('titular', 'titular')], max_length=20)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idEstudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ci', models.CharField(max_length=11, unique=True, verbose_name='Carnet identidad')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('agno_academico', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('clase', models.ManyToManyField(to='unissApp.clase', verbose_name='Clases')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unissApp.disciplina'),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unissApp.profesor'),
        ),
    ]
