# Generated by Django 4.2 on 2023-06-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unissApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='clase',
            field=models.ManyToManyField(blank=True, to='unissApp.clase', verbose_name='Clases'),
        ),
    ]
